# Generated by Django 4.2.1 on 2023-06-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_packagetype_tbl_subpackagetype_and_more'),
        ('Guest', '0002_tbk_agencyregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbk_agencyRegister',
            new_name='tbl_agencyRegister',
        ),
    ]
