# Generated by Django 4.2.1 on 2023-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_rename_tbk_agencyregister_tbl_agencyregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_agencyregister',
            name='agency_contact',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
