# Generated by Django 4.2.1 on 2023-06-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_tbl_agencyregister_agency_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_agencyregister',
            name='agency_status',
            field=models.IntegerField(default=0),
        ),
    ]
