# Generated by Django 4.2.1 on 2023-06-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_agencyregister_agency_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_userregister',
            name='user_gender',
        ),
    ]
