# Generated by Django 4.2.1 on 2023-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_remove_tbl_userregister_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_mail', models.EmailField(max_length=254, unique=True)),
                ('admin_passwd', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
