# Generated by Django 4.2.1 on 2023-06-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agency', '0016_tbl_packagedetails_package_status'),
        ('Guest', '0007_tbl_agencyregister_agency_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packagebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbooking_date', models.DateField(auto_now=True)),
                ('pbooking_status', models.IntegerField(default=0)),
                ('pbooking_fordate', models.DateField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agency.tbl_packagedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregister')),
            ],
        ),
    ]
