# Generated by Django 4.2.1 on 2023-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_packagebooking',
            name='pbooking_loc',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
