# Generated by Django 4.2.1 on 2023-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_packagebooking_pbooking_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_packagebooking',
            name='pbooing_amount',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
