# Generated by Django 4.2.1 on 2023-06-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_packagebooking_pbooing_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_packagebooking',
            old_name='pbooing_amount',
            new_name='pbooking_amount',
        ),
    ]
