# Generated by Django 4.2.1 on 2023-06-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_busbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_busbooking',
            name='bbooking_amount',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_busbooking',
            name='btotal_amount',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
