# Generated by Django 4.2.1 on 2023-06-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_tbl_busbooking_bbooking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_busbooking',
            name='from_loc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
