# Generated by Django 4.2.1 on 2023-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_tbl_busbooking_from_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_busbooking',
            name='purpose',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
