# Generated by Django 4.2.1 on 2023-06-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0018_remove_tbl_busdetails_bus_rate'),
        ('Guest', '0007_tbl_agencyregister_agency_status'),
        ('User', '0010_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.TextField()),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_reply', models.TextField(null=True)),
                ('complaint_date', models.DateField(auto_now=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_agencyregister')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agency.tbl_busdetails')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agency.tbl_packagedetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregister')),
            ],
        ),
    ]
