# Generated by Django 4.2.1 on 2023-06-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
