# Generated by Django 4.2.1 on 2023-06-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_complaint_email_tbl_complaint_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_payement',
            old_name='admin_profit',
            new_name='host_profit',
        ),
        migrations.AddField(
            model_name='tbl_payement',
            name='bbooking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_busbooking'),
        ),
        migrations.AlterField(
            model_name='tbl_payement',
            name='pbooking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_packagebooking'),
        ),
    ]
