# Generated by Django 4.2.1 on 2023-07-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_packagebooking',
            name='ppeople',
            field=models.IntegerField(null=True),
        ),
    ]
