# Generated by Django 4.2.1 on 2023-07-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_packagebooking_ppeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_packagebooking',
            old_name='ppeople',
            new_name='ppassengers',
        ),
    ]
