# Generated by Django 4.2.1 on 2023-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_rename_ppeople_tbl_packagebooking_ppassengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
