# Generated by Django 4.2.1 on 2023-06-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0007_tbl_agencyregister_agency_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hoteldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_address', models.TextField()),
                ('hotel_roomrate', models.CharField(max_length=30)),
                ('hotel_photos', models.FileField(upload_to='agencyhoteldocs/')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_agencyregister')),
            ],
        ),
    ]
