# Generated by Django 4.2.1 on 2023-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_hoteldetails',
            name='hotel_phno',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
