# Generated by Django 4.2.1 on 2023-06-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_agencyregister_agency_status'),
        ('Agency', '0002_tbl_hoteldetails_hotel_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mealdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=50)),
                ('meal_rate', models.CharField(max_length=30)),
                ('meal_photos', models.FileField(upload_to='agencymeals/')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_agencyregister')),
            ],
        ),
    ]
