# Generated by Django 4.2.1 on 2023-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0004_tbl_packagedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_packagedetails',
            name='hotel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_packagedetails',
            name='meal',
            field=models.CharField(max_length=200),
        ),
    ]
