# Generated by Django 4.2.1 on 2023-06-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0006_remove_tbl_packagedetails_hotel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_packagedetails',
        ),
    ]
