# Generated by Django 4.2.1 on 2023-06-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_agencyregister_agency_status'),
        ('Admin', '0005_tbl_packagetype_tbl_subpackagetype_and_more'),
        ('Agency', '0007_delete_tbl_packagedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packagedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('package_description', models.TextField()),
                ('package_cover', models.FileField(upload_to='packagedocs/')),
                ('package_locations', models.TextField()),
                ('package_days', models.CharField(max_length=20)),
                ('package_nights', models.CharField(max_length=20)),
                ('hotel', models.CharField(max_length=50)),
                ('package_price', models.CharField(max_length=30)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_agencyregister')),
                ('meal', models.ManyToManyField(to='Agency.tbl_mealdetails')),
                ('packagetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_packagetype')),
            ],
        ),
    ]
