# Generated by Django 4.2.1 on 2023-06-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0008_tbl_packagedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_packagedetails',
        ),
    ]
