# Generated by Django 4.2.1 on 2023-06-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0010_tbl_packagedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dayhighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.CharField(max_length=20)),
                ('day_highlights', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agency.tbl_packagedetails')),
            ],
        ),
    ]
