# Generated by Django 4.2.1 on 2023-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0013_remove_tbl_hoteldetails_hotel_roomrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_packagedetails',
            name='bus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_packagedetails',
            name='package_persons',
            field=models.IntegerField(null=True),
        ),
    ]
