# Generated by Django 4.2.1 on 2023-06-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_agencyregister_agency_status'),
        ('Agency', '0014_tbl_packagedetails_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_busdetails',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_agencyregister'),
        ),
    ]
