# Generated by Django 4.2.1 on 2023-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0015_tbl_busdetails_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_packagedetails',
            name='package_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
