# Generated by Django 4.2.1 on 2023-06-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0017_tbl_busdetails_bus_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_busdetails',
            name='bus_rate',
        ),
    ]
