# Generated by Django 4.2.1 on 2023-07-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0019_tbl_dayhighlights_day_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_packagedetails',
            name='packagetype',
        ),
    ]
