# Generated by Django 4.2.1 on 2023-07-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0020_remove_tbl_packagedetails_packagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_busdetails',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agency.tbl_packagedetails'),
        ),
    ]
