# Generated by Django 4.2.1 on 2023-07-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0021_tbl_busdetails_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mealdetails',
            name='meal_photos',
        ),
    ]
