# Generated by Django 4.2.1 on 2023-08-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0022_remove_tbl_mealdetails_meal_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_hoteldetails',
            name='hotel_photos',
        ),
    ]
