# Generated by Django 4.2.1 on 2023-06-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packagetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagetype_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subpackagetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpackagetype_name', models.CharField(max_length=40)),
                ('packagetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_packagetype')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
