# Generated by Django 4.2.1 on 2023-07-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_packagetype_tbl_subpackagetype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subpackagetype',
        ),
    ]
